export const firstAidList = [
  'CPR',
  'Poisoning',
  'Choking',
  'Stings',
  'Dog Bites',
  'Fractures & Broken Bones',
  'Food Poisoning',
  'Heat Stroke',
  'Shock',
  'Bleeding',
  'Having a Seizure',
  'Drowning',
  'Ear Injuries',
  'Eye Injuries',
];
